sudo: required

services:
  - docker

before_install:
  # run tests inside client container
  - docker build -t alexblaze1994/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alexblaze1994/react-test npm test

after_success:
  - docker build -t alexblaze1994/client-prod ./client
  - docker build -t alexblaze1994/nginx-prod ./nginx
  - docker build -t alexblaze1994/server-prod ./server
  - docker build -t alexblaze1994/worker-prod ./worker
  # log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those image and push them to dockerhub
  - docker push -t alexblaze1994/client-prod
  - docker push -t alexblaze1994/nginx-prod
  - docker push -t alexblaze1994/server-prod
  - docker push -t alexblaze1994/worker-prod

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multicontainer
  env: Multicontainer-env
  bucket_name: elasticbeanstalk-us-east-2-184626414275
  #can be any
  bucket_path: docker-multi
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY


